### ISSUE TITLE
Ошибка загрузки данных

### ISSUE THREAD

**Issue by RockZe** [EvilToasterDBU/D4Launcher#7]
Не знаю в чем проблема, но на этапе ЛОГИНа (переустановил винду, слетел sso ключ) выдает вот такую вот ошибку
![image](https://github.com/EvilToasterDBU/D4Launcher/assets/123874691/d269a251-bd32-417a-b6ae-f7c63bcaa200)
Может кто-то знает, в чем проблема?

**Comment by Video-VV** [comment]
при попытке "Установить", не работает скачивание... выдаёт ошибку.

```
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)


************** Загруженные сборки **************
System.Private.CoreLib
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
D4Launcher
    Версия сборки: 1.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Collections
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Threading
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Security.Cryptography.Csp
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Security.Cryptography.Algorithms
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Security.Cryptography.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Memory
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
DarkNet
    Версия сборки: 2.2.0.0
    Версия Win32: 2.2.0.0
    CodeBase (база кода): file:///C:/Temp/Costura/E71550CC52DFE0972B945D5077B98D28/darknet.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 6.0.2.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.ComponentModel.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Windows.Forms.Primitives
    Версия сборки: 6.0.2.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime.InteropServices
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Drawing.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Collections.Specialized
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Diagnostics.TraceSource
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Collections.Concurrent
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Microsoft.Win32.SystemEvents
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Threading.Thread
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Drawing.Common
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Resources.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Drawing
    Версия сборки: 6.0.2.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Microsoft.Win32.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.ComponentModel.TypeConverter
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Dark Mode UI
    Версия сборки: 3.1.0.0
    Версия Win32: 3.1.0.0
    CodeBase (база кода): file:///C:/Temp/Costura/E71550CC52DFE0972B945D5077B98D28/dark%20mode%20ui.dll
----------------------------------------
System.ComponentModel
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Numerics.Vectors
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.ObjectModel
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Linq
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Microsoft.Win32.Registry
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Collections.NonGeneric
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Версия сборки: 7.0.4.0
    Версия Win32: 7.0.4
    CodeBase (база кода): file:///C:/Temp/Costura/E71550CC52DFE0972B945D5077B98D28/microsoft.windowsapicodepack.shell.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Net.Http
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Net.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Newtonsoft.Json
    Версия сборки: 13.0.0.0
    Версия Win32: 13.0.3.27908
    CodeBase (база кода): file:///C:/Temp/Costura/E71550CC52DFE0972B945D5077B98D28/newtonsoft.json.dll
----------------------------------------
System.Linq.Expressions
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Diagnostics.Tracing
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Diagnostics.DiagnosticSource
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Net.Security
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Security.Cryptography.X509Certificates
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Private.Uri
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Net.Sockets
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Threading.Overlapped
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Net.NameResolution
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Threading.ThreadPool
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Security.Principal.Windows
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Security.Claims
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Security.Cryptography.Encoding
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime.Numerics
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Microsoft.WindowsAPICodePack.Core
    Версия сборки: 7.0.4.0
    Версия Win32: 7.0.4
    CodeBase (база кода): file:///C:/Temp/Costura/E71550CC52DFE0972B945D5077B98D28/microsoft.windowsapicodepack.core.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Diagnostics.Process
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Xml.ReaderWriter
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Private.Xml
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Text.RegularExpressions
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Net.WebClient
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Text.Encoding.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime.Serialization.Formatters
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Xml.XmlSerializer
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Windows.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Console
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime.Loader
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 6.0.2.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Diagnostics.StackTrace
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Reflection.Metadata
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Collections.Immutable
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Net.Quic
    Версия сборки: 6.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------

************** Оперативная отладка (JIT) **************



```
